src/ActiveLogin.Authentication.BankId.Api/BankIdApiClient.cs, src/ActiveLogin.Authentication.BankId.Api/BankIdApiClientExtensions.cs, src/ActiveLogin.Authentication.BankId.Api/BankIdApiException.cs, src/ActiveLogin.Authentication.BankId.Api/BankIdUrls.cs, src/ActiveLogin.Authentication.BankId.Api/Errors/BankIdApiErrorHandler.cs, src/ActiveLogin.Authentication.BankId.Api/FakeBankIdApiClient.cs, src/ActiveLogin.Authentication.BankId.Api/HttpClientExtensions.cs, src/ActiveLogin.Authentication.BankId.Api/IBankIdApiClient.cs, src/ActiveLogin.Authentication.BankId.Api/Models/AuthRequest.cs, src/ActiveLogin.Authentication.BankId.Api/Models/AuthResponse.cs, src/ActiveLogin.Authentication.BankId.Api/Models/CancelRequest.cs, src/ActiveLogin.Authentication.BankId.Api/Models/CancelResponse.cs, src/ActiveLogin.Authentication.BankId.Api/Models/Cert.cs, src/ActiveLogin.Authentication.BankId.Api/Models/CollectHintCode.cs, src/ActiveLogin.Authentication.BankId.Api/Models/CollectRequest.cs, src/ActiveLogin.Authentication.BankId.Api/Models/CollectResponse.cs, src/ActiveLogin.Authentication.BankId.Api/Models/CollectStatus.cs, src/ActiveLogin.Authentication.BankId.Api/Models/CompletionData.cs, src/ActiveLogin.Authentication.BankId.Api/Models/Device.cs, src/ActiveLogin.Authentication.BankId.Api/Models/ErrorCode.cs, src/ActiveLogin.Authentication.BankId.Api/Models/MessageShortName.cs, src/ActiveLogin.Authentication.BankId.Api/Models/Requirement.cs, src/ActiveLogin.Authentication.BankId.Api/Models/User.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Areas/BankIdAuthentication/Controllers/BankIdApiController.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Areas/BankIdAuthentication/Controllers/BankIdController.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/BankIdAuthenticationConstants.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/BankIdAuthenticationHandler.cs
* Refactor implementation
* Add documentation
=> Refactor BankID authentication

README.md
We found it very hard no normalize the names in a general way, therefore we choose to (at this point) to rather show an example on how you can do it in some scenarios rather than implementing it as part of the core package.
Solves #31.
=> Document how to normalize names

samples/MvcClientSample/Controllers/AccountController.cs, samples/MvcClientSample/Startup.cs
Reviewed the schemas that we use and tried to avoid hardcoding. Using predefined defaults now
=> Remove hardcoded auth schemas

src/ActiveLogin.Authentication.BankId.AspNetCore/Areas/BankIdAuthentication/Controllers/BankIdApiController.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Areas/BankIdAuthentication/Views/BankId/_LoginScript.cshtml, src/ActiveLogin.Authentication.BankId.AspNetCore/BankIdLauncher.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Models/BankIdLoginApiInitializeResponse.cs
BankID on desktop did open a new tab on completion. This changes the redirect behaviour to fix this.
=> Fix BankID on desktop

src/ActiveLogin.Authentication.BankId.AspNetCore/Areas/BankIdAuthentication/Views/BankId/_LoginScript.cshtml
We had a bug where we did not show that the PIN was invalid. Now fixed.
=> Handle invalid PINs

samples/IdentityServerSample/Views/Account/Login.cshtml, samples/IdentityServerSample/Views/Shared/_Layout.cshtml, samples/IdentityServerSample/Views/Shared/_LayoutMaster.cshtml, src/ActiveLogin.Authentication.BankId.AspNetCore/Areas/BankIdAuthentication/Views/BankId/Login.cshtml, src/ActiveLogin.Authentication.BankId.AspNetCore/Areas/BankIdAuthentication/Views/BankId/_Login.cshtml, src/ActiveLogin.Authentication.BankId.AspNetCore/Areas/BankIdAuthentication/Views/BankId/_LoginForm.cshtml
=> Remove need for styles section

src/ActiveLogin.Authentication.BankId.AspNetCore/Areas/BankIdAuthentication/Controllers/BankIdApiController.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Areas/BankIdAuthentication/Controllers/BankIdController.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Areas/BankIdAuthentication/Models/BankIdLoginViewModel.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Areas/BankIdAuthentication/Views/BankId/_LoginForm.cshtml, src/ActiveLogin.Authentication.BankId.AspNetCore/Areas/BankIdAuthentication/Views/BankId/_LoginScript.cshtml, src/ActiveLogin.Authentication.BankId.AspNetCore/BankIdLauncher.cs
Fixes #58.
Also changes what redirectUri is set to follow the recomendations from Bankd docs.
=> Fix phone tab issue

samples/Standalone.MvcSample/Standalone.MvcSample.csproj, samples/Standalone.MvcSample/Views/Shared/_Layout.cshtml, src/ActiveLogin.Authentication.BankId.AspNetCore/BankIdDevelopmentLauncher.cs
Also fixes some sample references.
Fixes #68
=> Fix bankid launch issue

README.md, docs/getting-started-bankid.md, docs/getting-started-grandid-bankid.md, samples/IdentityServer.ServerSample/Startup.cs, samples/IdentityServer.ServerSample/appsettings.json, samples/Standalone.MvcSample/Startup.cs, samples/Standalone.MvcSample/appsettings.json, src/ActiveLogin.Authentication.BankId.Api/BankIdSimulatedApiClient.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/BankIdAuthenticationBuilderEnvironmentExtensions.cs, src/ActiveLogin.Authentication.GrandId.Api/GrandIdSimulatedApiClient.cs, src/ActiveLogin.Authentication.GrandId.AspNetCore/GrandIdAuthenticationBuilderEnvironmentExtensions.cs, test/ActiveLogin.Authentication.BankId.Api.Test/BankIdSimulatedApiClient_Tests.cs, test/ActiveLogin.Authentication.BankId.AspNetCore.Test/BankId_Authentication_Tests.cs, test/ActiveLogin.Authentication.GrandId.Api.Test/GrandIdSimulatedApiClient_Tests.cs, test/ActiveLogin.Authentication.GrandId.AspNetCore.Test/GrandId_Authentication_Tests.cs
=> Rename DevelopmentEnvironment into SimulatedEnvironment

src/ActiveLogin.Authentication.BankId.AspNetCore/BankIdAuthenticationDefaults.cs
Change default texts to be in Swedish (#78)
=> Update default texts (For 2.0)

src/ActiveLogin.Authentication.BankId.AspNetCore/Areas/BankIdAuthentication/Controllers/BankIdController.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Areas/BankIdAuthentication/Views/BankId/Login.cshtml, src/ActiveLogin.Authentication.BankId.AspNetCore/Resources/BankIdAuthenticationHandler.Designer.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Resources/BankIdAuthenticationHandler.resx, src/ActiveLogin.Authentication.BankId.AspNetCore/Resources/BankIdAuthenticationHandler.sv.resx
=> Fix typos in "magic strings"

src/ActiveLogin.Authentication.BankId.AspNetCore/Areas/BankIdAuthentication/Controllers/BankIdController.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Areas/BankIdAuthentication/Models/BankIdLoginScriptOptions.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Areas/BankIdAuthentication/Views/BankId/_LoginScript.cshtml
also for #93 
More typos found
=> additonal typos found

src/ActiveLogin.Authentication.BankId.AspNetCore/ActiveLogin.Authentication.BankId.AspNetCore.csproj, src/ActiveLogin.Authentication.BankId.AspNetCore/Areas/BankIdAuthentication/Controllers/BankIdApiController.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Areas/BankIdAuthentication/Controllers/BankIdController.cs
=> Fix BankID API URLs and make sure they wortk corss Core 2.2 and 3.0

src/ActiveLogin.Authentication.BankId.Api/ActiveLogin.Authentication.BankId.Api.csproj, src/ActiveLogin.Authentication.BankId.AspNetCore.Azure/ActiveLogin.Authentication.BankId.AspNetCore.Azure.csproj, src/ActiveLogin.Authentication.BankId.AspNetCore/ActiveLogin.Authentication.BankId.AspNetCore.csproj, src/ActiveLogin.Authentication.GrandId.Api/ActiveLogin.Authentication.GrandId.Api.csproj, src/ActiveLogin.Authentication.GrandId.AspNetCore/ActiveLogin.Authentication.GrandId.AspNetCore.csproj
Sets explicit assembly versions for all packages.
=> Add explicit assembly version

azure-pipelines.yml
=> Use YAML for Azure Pipelines

ActiveLogin.Authentication.sln, README.md, global.json, samples/IdentityServer.ClientSample/IdentityServer.ClientSample.csproj, samples/IdentityServer.ServerSample/IdentityServer.ServerSample.csproj, samples/Standalone.MvcSample/Standalone.MvcSample.csproj, src/ActiveLogin.Authentication.BankId.Api/ActiveLogin.Authentication.BankId.Api.csproj, src/ActiveLogin.Authentication.BankId.AspNetCore.Azure/ActiveLogin.Authentication.BankId.AspNetCore.Azure.csproj, src/ActiveLogin.Authentication.BankId.AspNetCore.QRCoder/ActiveLogin.Authentication.BankId.AspNetCore.QRCoder.csproj, src/ActiveLogin.Authentication.BankId.AspNetCore/ActiveLogin.Authentication.BankId.AspNetCore.csproj, src/ActiveLogin.Authentication.GrandId.Api/ActiveLogin.Authentication.GrandId.Api.csproj, src/ActiveLogin.Authentication.GrandId.AspNetCore/ActiveLogin.Authentication.GrandId.AspNetCore.csproj, test/ActiveLogin.Authentication.BankId.Api.Test/ActiveLogin.Authentication.BankId.Api.Test.csproj, test/ActiveLogin.Authentication.BankId.AspNetCore.Azure.Test/ActiveLogin.Authentication.BankId.AspNetCore.Azure.Test.csproj, test/ActiveLogin.Authentication.BankId.AspNetCore.Test/ActiveLogin.Authentication.BankId.AspNetCore.Test.csproj, test/ActiveLogin.Authentication.GrandId.Api.Test/ActiveLogin.Authentication.GrandId.Api.Test.csproj, test/ActiveLogin.Authentication.GrandId.AspNetCore.Test/ActiveLogin.Authentication.GrandId.AspNetCore.Test.csproj
Fixes #133 
Also harmonizes project files, descriptions, warnings etc.
=> Update target frameworks and cleanup project files

README.md, docs/getting-started-bankid.md, docs/getting-started-grandid-bankid.md, samples/IdentityServer.ServerSample/Controllers/AccountController.cs, samples/IdentityServer.ServerSample/Startup.cs, samples/Standalone.MvcSample/Startup.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Areas/BankIdAuthentication/Controllers/BankIdApiController.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Areas/BankIdAuthentication/Controllers/BankIdController.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Areas/BankIdAuthentication/Models/BankIdLoginViewModel.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Areas/BankIdAuthentication/Views/BankId/_LoginScript.cshtml, src/ActiveLogin.Authentication.BankId.AspNetCore/Areas/BankIdAuthentication/Views/BankId/_LoginStatus.cshtml, src/ActiveLogin.Authentication.BankId.AspNetCore/BankIdAuthenticationBuilderExtensions.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/BankIdAuthenticationConstants.cs, test/ActiveLogin.Authentication.BankId.AspNetCore.Test/BankId_Authentication_Tests.cs
Fixes a few minor things I found while testing out the alpha.
=> Fix minor bugs

samples/IdentityServer.ServerSample/Views/Shared/_LayoutMaster.cshtml, samples/Standalone.MvcSample/Views/Shared/_Layout.cshtml
=> Move polyfills to head

src/ActiveLogin.Authentication.BankId.AspNetCore/BankIdAuthenticationBuilder.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/BankIdAuthenticationBuilderExtensions.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Cryptography/X509CertificateChainValidator.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/IBankIdAuthenticationBuilder.cs, src/ActiveLogin.Authentication.GrandId.AspNetCore/GrandIdAuthenticationBuilder.cs, src/ActiveLogin.Authentication.GrandId.AspNetCore/IGrandIdAuthenticationBuilder.cs
Use SocketsHttpHandler instead of old HttpClientHandler.
Fixes #173.
=> Use SocketsHttpHandler

samples/IdentityServer.ServerSample/Startup.cs, samples/Standalone.MvcSample/Startup.cs, src/ActiveLogin.Authentication.BankId.AspNetCore.Azure/BankIdAuthenticationBuilderAzureExtensions.cs, src/ActiveLogin.Authentication.BankId.AspNetCore.QRCoder/BankIdAuthenticationBuilderQrCoderExtensions.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/BankIdAuthenticationBuilderEnvironmentExtensions.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/BankIdAuthenticationBuilderExtensions.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/BankIdAuthenticationBuilderSchemeExtensions.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/BankIdAuthenticationExtensions.cs, src/ActiveLogin.Authentication.GrandId.AspNetCore/GrandIdAuthenticationBuilderEnvironmentExtensions.cs, src/ActiveLogin.Authentication.GrandId.AspNetCore/GrandIdAuthenticationBuilderExtensions.cs, src/ActiveLogin.Authentication.GrandId.AspNetCore/GrandIdAuthenticationBuilderSchemeExtensions.cs, src/ActiveLogin.Authentication.GrandId.AspNetCore/GrandIdAuthenticationExtensions.cs
=> Move namespaces for auth extensions

global.json, samples/IdentityServer.ClientSample/IdentityServer.ClientSample.csproj, src/ActiveLogin.Authentication.BankId.Api/ActiveLogin.Authentication.BankId.Api.csproj, src/ActiveLogin.Authentication.BankId.AspNetCore.Azure/ActiveLogin.Authentication.BankId.AspNetCore.Azure.csproj, src/ActiveLogin.Authentication.BankId.AspNetCore.QRCoder/ActiveLogin.Authentication.BankId.AspNetCore.QRCoder.csproj, src/ActiveLogin.Authentication.BankId.AspNetCore/ActiveLogin.Authentication.BankId.AspNetCore.csproj, src/ActiveLogin.Authentication.GrandId.Api/ActiveLogin.Authentication.GrandId.Api.csproj, src/ActiveLogin.Authentication.GrandId.AspNetCore/ActiveLogin.Authentication.GrandId.AspNetCore.csproj, test/ActiveLogin.Authentication.BankId.AspNetCore.Test/ActiveLogin.Authentication.BankId.AspNetCore.Test.csproj, test/ActiveLogin.Authentication.GrandId.AspNetCore.Test/ActiveLogin.Authentication.GrandId.AspNetCore.Test.csproj
And set package versions to beta 1.
=> Bump versions to 3.1.0

src/ActiveLogin.Authentication.BankId.Api/Models/ErrorCode.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Areas/BankIdAuthentication/Controllers/BankIdApiController.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Areas/BankIdAuthentication/Views/BankId/_Login.cshtml, src/ActiveLogin.Authentication.BankId.AspNetCore/Areas/BankIdAuthentication/Views/BankId/_LoginScript.cshtml, src/ActiveLogin.Authentication.BankId.AspNetCore/BankIdLoggingEvents.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Launcher/BankIdDevelopmentLauncher.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Launcher/BankIdLauncher.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/LoggerExtensions.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/SupportedDevice/BankIdSupportedDevice.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/SupportedDevice/BankIdSupportedDeviceDetector.cs, test/ActiveLogin.Authentication.BankId.AspNetCore.Test/UserMessage/BankIdSupportedDeviceDetector_Detect_Tests.cs
This PR fixes things from #181 and #185.
=> Refactor device detection and try to fix bug

README.md, samples/IdentityServer.ClientSample/Startup.cs, samples/IdentityServer.ServerSample/Startup.cs, samples/Standalone.MvcSample/Startup.cs
=> Readme fixes

src/ActiveLogin.Authentication.BankId.Api/UserMessage/BankIdRecommendedUserMessage.cs, src/ActiveLogin.Authentication.BankId.Api/UserMessage/MessageShortName.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Areas/BankIdAuthentication/Controllers/BankIdController.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Areas/BankIdAuthentication/Views/BankId/_LoginScript.cshtml, src/ActiveLogin.Authentication.BankId.AspNetCore/Resources/BankIdHandler.Designer.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Resources/BankIdHandler.resx, src/ActiveLogin.Authentication.BankId.AspNetCore/Resources/BankIdHandler.sv.resx
=> Improve QR and message

samples/IdentityServer.ServerSample/IdentityServer.ServerSample.csproj, src/ActiveLogin.Authentication.BankId.Api/ActiveLogin.Authentication.BankId.Api.csproj, src/ActiveLogin.Authentication.BankId.AspNetCore.Azure/ActiveLogin.Authentication.BankId.AspNetCore.Azure.csproj, src/ActiveLogin.Authentication.BankId.AspNetCore.QRCoder/ActiveLogin.Authentication.BankId.AspNetCore.QRCoder.csproj, src/ActiveLogin.Authentication.BankId.AspNetCore/ActiveLogin.Authentication.BankId.AspNetCore.csproj, src/ActiveLogin.Authentication.GrandId.Api/ActiveLogin.Authentication.GrandId.Api.csproj, src/ActiveLogin.Authentication.GrandId.AspNetCore/ActiveLogin.Authentication.GrandId.AspNetCore.csproj
=> Bump versions for beta 2

LICENSE.md, README.md, src/ActiveLogin.Authentication.BankId.Api/ActiveLogin.Authentication.BankId.Api.csproj, src/ActiveLogin.Authentication.BankId.AspNetCore.Azure/ActiveLogin.Authentication.BankId.AspNetCore.Azure.csproj, src/ActiveLogin.Authentication.BankId.AspNetCore.QRCoder/ActiveLogin.Authentication.BankId.AspNetCore.QRCoder.csproj, src/ActiveLogin.Authentication.BankId.AspNetCore/ActiveLogin.Authentication.BankId.AspNetCore.csproj, src/ActiveLogin.Authentication.GrandId.Api/ActiveLogin.Authentication.GrandId.Api.csproj, src/ActiveLogin.Authentication.GrandId.AspNetCore/ActiveLogin.Authentication.GrandId.AspNetCore.csproj
=> Update csproj info and readme

docs/getting-started-bankid.md, src/ActiveLogin.Authentication.BankId.Api/ActiveLogin.Authentication.BankId.Api.csproj, src/ActiveLogin.Authentication.BankId.AspNetCore.Azure/ActiveLogin.Authentication.BankId.AspNetCore.Azure.csproj, src/ActiveLogin.Authentication.BankId.AspNetCore/ActiveLogin.Authentication.BankId.AspNetCore.csproj
=> Docs on managed identity

README.md
=> Update with info on V5

src/ActiveLogin.Authentication.BankId.Api/ActiveLogin.Authentication.BankId.Api.csproj, src/ActiveLogin.Authentication.BankId.AspNetCore.Azure/ActiveLogin.Authentication.BankId.AspNetCore.Azure.csproj, src/ActiveLogin.Authentication.BankId.AspNetCore.QRCoder/ActiveLogin.Authentication.BankId.AspNetCore.QRCoder.csproj, src/ActiveLogin.Authentication.BankId.AspNetCore/ActiveLogin.Authentication.BankId.AspNetCore.csproj, src/ActiveLogin.Authentication.GrandId.Api/ActiveLogin.Authentication.GrandId.Api.csproj, src/ActiveLogin.Authentication.GrandId.AspNetCore/ActiveLogin.Authentication.GrandId.AspNetCore.csproj
This PR removes the version suffix.
=> Bump to v3

README.md
=> Added FAQ on Linux dependencies

README.md
=> Add info on FAQ

docs/getting-started-bankid.md, samples/IdentityServer.ClientSample/appsettings.Development.json, samples/IdentityServer.ClientSample/appsettings.json, samples/IdentityServer.ServerSample/appsettings.Development.json, samples/IdentityServer.ServerSample/appsettings.json, samples/Standalone.MvcSample/appsettings.Development.json, samples/Standalone.MvcSample/appsettings.json, src/ActiveLogin.Authentication.BankId.AspNetCore.Azure/ActiveLogin.Authentication.BankId.AspNetCore.Azure.csproj, src/ActiveLogin.Authentication.BankId.AspNetCore.QRCoder/ActiveLogin.Authentication.BankId.AspNetCore.QRCoder.csproj, src/ActiveLogin.Authentication.BankId.AspNetCore/ActiveLogin.Authentication.BankId.AspNetCore.csproj, src/ActiveLogin.Authentication.BankId.AspNetCore/Areas/BankIdAuthentication/Controllers/BankIdApiController.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/BankIdBuilderExtensions.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/BankIdExtensions.cs
=> Make it easier to use IBankIdResultStore

docs/getting-started-bankid.md, src/ActiveLogin.Authentication.BankId.AspNetCore/Areas/BankIdAuthentication/Controllers/BankIdApiController.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/BankIdBuilderExtensions.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/EndUserContext/DynamicEndUserIpResolver.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/EndUserContext/IEndUserIpResolver.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/EndUserContext/RemoteIpAddressEndUserIpResolver.cs
=> Allow overriding retreival of EndUserIp

docs/getting-started-bankid.md, src/ActiveLogin.Authentication.BankId.AspNetCore/BankIdBuilderExtensions.cs
=> Remove UseClientCertificateResolver

src/ActiveLogin.Authentication.BankId.AspNetCore/Areas/BankIdAuthentication/Views/BankId/_LoginScript.cshtml
=> Enables cancel button even when init fails

README.md, src/ActiveLogin.Authentication.BankId.AspNetCore.AzureMonitor/ApplicationInsightsBankIdEventListenerOptions.cs, src/ActiveLogin.Authentication.BankId.AspNetCore.AzureMonitor/BankIdApplicationInsightsEventListener.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/SupportedDevice/BankIdSupportedDevice.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/SupportedDevice/IBankIdSupportedDeviceDetector.cs
=> Rename device properties

src/ActiveLogin.Authentication.BankId.AspNetCore/Launcher/BankIdDevelopmentLauncher.cs
Bug in simulated enviroment when selecting same device. Page is reloaded which triggers a new login attempt. The login attempt fails since a login is already in progress.
=> Bug in simulated enviroment when selecting same device.

src/ActiveLogin.Authentication.BankId.AspNetCore.AzureMonitor/BankIdApplicationInsightsEventListener.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Events/Infrastructure/BankIdEventTypes.cs
=> Add error properties before tracking event

src/ActiveLogin.Authentication.BankId.Api/ActiveLogin.Authentication.BankId.Api.csproj, src/ActiveLogin.Authentication.BankId.AspNetCore.Azure/ActiveLogin.Authentication.BankId.AspNetCore.Azure.csproj, src/ActiveLogin.Authentication.BankId.AspNetCore.AzureMonitor/ActiveLogin.Authentication.BankId.AspNetCore.AzureMonitor.csproj, src/ActiveLogin.Authentication.BankId.AspNetCore.QRCoder/ActiveLogin.Authentication.BankId.AspNetCore.QRCoder.csproj, src/ActiveLogin.Authentication.BankId.AspNetCore.UAParser/ActiveLogin.Authentication.BankId.AspNetCore.UAParser.csproj, src/ActiveLogin.Authentication.BankId.AspNetCore/ActiveLogin.Authentication.BankId.AspNetCore.csproj, src/ActiveLogin.Authentication.GrandId.Api/ActiveLogin.Authentication.GrandId.Api.csproj, src/ActiveLogin.Authentication.GrandId.AspNetCore/ActiveLogin.Authentication.GrandId.AspNetCore.csproj
New version suffix release candidate 1.
=> Changed version suffix.

samples/IdentityServer.ClientSample/IdentityServer.ClientSample.csproj, samples/IdentityServer.ServerSample/IdentityServer.ServerSample.csproj, src/ActiveLogin.Authentication.BankId.Api/ActiveLogin.Authentication.BankId.Api.csproj, src/ActiveLogin.Authentication.BankId.AspNetCore.Azure/ActiveLogin.Authentication.BankId.AspNetCore.Azure.csproj, src/ActiveLogin.Authentication.BankId.AspNetCore.AzureMonitor/ActiveLogin.Authentication.BankId.AspNetCore.AzureMonitor.csproj, src/ActiveLogin.Authentication.BankId.AspNetCore.QRCoder/ActiveLogin.Authentication.BankId.AspNetCore.QRCoder.csproj, src/ActiveLogin.Authentication.BankId.AspNetCore.UAParser/ActiveLogin.Authentication.BankId.AspNetCore.UAParser.csproj, src/ActiveLogin.Authentication.BankId.AspNetCore/ActiveLogin.Authentication.BankId.AspNetCore.csproj, src/ActiveLogin.Authentication.GrandId.Api/ActiveLogin.Authentication.GrandId.Api.csproj, src/ActiveLogin.Authentication.GrandId.AspNetCore/ActiveLogin.Authentication.GrandId.AspNetCore.csproj, test/ActiveLogin.Authentication.BankId.Api.Test/ActiveLogin.Authentication.BankId.Api.Test.csproj, test/ActiveLogin.Authentication.BankId.AspNetCore.Azure.Test/ActiveLogin.Authentication.BankId.AspNetCore.Azure.Test.csproj, test/ActiveLogin.Authentication.BankId.AspNetCore.Test/ActiveLogin.Authentication.BankId.AspNetCore.Test.csproj, test/ActiveLogin.Authentication.BankId.BankId.AspNetCore.UAParser.Test/ActiveLogin.Authentication.BankId.BankId.AspNetCore.UAParser.Test.csproj, test/ActiveLogin.Authentication.GrandId.Api.Test/ActiveLogin.Authentication.GrandId.Api.Test.csproj, test/ActiveLogin.Authentication.GrandId.AspNetCore.Test/ActiveLogin.Authentication.GrandId.AspNetCore.Test.csproj
=> Release v4

docs/getting-started-bankid.md
=> Update FAQ with certificate handling when running in Linux

src/ActiveLogin.Authentication.BankId.AspNetCore/Areas/BankIdAuthentication/Controllers/BankIdApiController.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/BankIdHandler.cs
=> Added missing awaits

docs/getting-started-bankid.md, src/ActiveLogin.Authentication.BankId.AspNetCore/ActiveLogin.Authentication.BankId.AspNetCore.csproj, src/ActiveLogin.Authentication.BankId.AspNetCore/Areas/BankIdAuthentication/Controllers/BankIdController.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/BankIdBuilderExtensions.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/BankIdHandler.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Models/BankIdLoginOptions.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Serialization/BankIdLoginOptionsSerializer.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/StateHandling/BankIdCancelUrlInvalidStateHandler.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/StateHandling/BankIdInvalidStateContext.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/StateHandling/IBankIdInvalidStateHandler.cs, test/ActiveLogin.Authentication.BankId.AspNetCore.Test/BankId_Authentication_Tests.cs
This PR fixes #301 and fixes #298.
=> Implement invalid state handling

samples/Standalone.MvcSample/Standalone.MvcSample.csproj, samples/Standalone.MvcSample/Startup.cs
=> added AddApplicationInsightsTelemetry to startup

src/ActiveLogin.Authentication.BankId.AspNetCore/ActiveLogin.Authentication.BankId.AspNetCore.csproj
=> Remove beta for 4.1.0 release

.github/workflows/build.yml, azure-pipelines.yml
=> Change master into main

samples/IdentityServer.ClientSample/Models/HomeIndexViewModel.cs, samples/IdentityServer.ClientSample/Views/Home/Index.cshtml, samples/IdentityServer.ServerSample/Models/HomeIndexViewModel.cs, samples/IdentityServer.ServerSample/Views/Home/Index.cshtml, src/ActiveLogin.Authentication.BankId.AspNetCore.AzureMonitor/BankIdApplicationInsightsEventListener.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/ActiveLogin.Authentication.BankId.AspNetCore.csproj, src/ActiveLogin.Authentication.BankId.AspNetCore/Areas/BankIdAuthentication/Controllers/BankIdApiController.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/BankIdHandler.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Events/BankIdAspNetAuthenticateSuccessEvent.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Events/BankIdAuthErrorEvent.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Events/BankIdAuthSuccessEvent.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Events/Infrastructure/BankIdDebugEventListener.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Models/BankIdLoginOptions.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Serialization/BankIdLoginOptionsSerializer.cs, src/ActiveLogin.Authentication.GrandId.AspNetCore/ActiveLogin.Authentication.GrandId.AspNetCore.csproj, src/ActiveLogin.Authentication.GrandId.AspNetCore/GrandIdBankIdHandler.cs, src/ActiveLogin.Authentication.GrandId.AspNetCore/GrandIdClaimTypes.cs
=> Update ActiveLogin Identity dependency

docs/bankid.md, samples/IdentityServer.ServerSample/appsettings.json, samples/Standalone.MvcSample/appsettings.json, src/ActiveLogin.Authentication.BankId.AspNetCore.Azure/AzureKeyVaultCertificateClient.cs, src/ActiveLogin.Authentication.BankId.AspNetCore.Azure/ClientCertificateFromAzureKeyVaultOptions.cs, src/ActiveLogin.Authentication.BankId.AspNetCore.Azure/ManagedIdentityType.cs, src/ActiveLogin.Authentication.BankId.AspNetCore.Azure/README.md, test/ActiveLogin.Authentication.BankId.AspNetCore.Azure.Test/BankIdAuthenticationBuilderAzureExtensions_Tests.cs
=> Use azure default credentials

.github/workflows/release.yml, ActiveLogin.Authentication.sln
This PR begins the work for #320.
=> Add release

README.md, src/ActiveLogin.Authentication.BankId.AspNetCore.QRCoder/QrCoderBankIdQrCodeGenerator.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Areas/BankIdAuthentication/Controllers/BankIdApiController.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Areas/BankIdAuthentication/Controllers/BankIdController.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Areas/BankIdAuthentication/Models/BankIdLoginApiInitializeResponse.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Areas/BankIdAuthentication/Models/BankIdLoginApiQrCodeRequest.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Areas/BankIdAuthentication/Models/BankIdLoginApiQrCodeResponse.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Areas/BankIdAuthentication/Models/BankIdLoginScriptOptions.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Areas/BankIdAuthentication/Views/BankId/_LoginScript.cshtml, src/ActiveLogin.Authentication.BankId.AspNetCore/BankIdBuilderExtensions.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/BankIdDefaults.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/DataProtection/BankIdQrStartStateProtector.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/DataProtection/IBankIdOrderRefProtector.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/DataProtection/IBankIdQrStartStateProtector.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Models/BankIdQrStartState.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Models/BankIdState.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Qr/BankIdMissingQrCodeGenerator.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Qr/BankIdQrCodeContentGenerator.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Qr/IBankIdQrCodeContentGenerator.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Qr/IBankIdQrCodeGenerator.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Serialization/BankIdOrderRefSerializer.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Serialization/BankIdQrStartStateSerializer.cs, test/ActiveLogin.Authentication.BankId.AspNetCore.Test/Qr/BankIdQrCodeContentGenerator_Tests.cs
=> Support animated QR codes

src/ActiveLogin.Authentication.BankId.Api/ActiveLogin.Authentication.BankId.Api.csproj, src/ActiveLogin.Authentication.BankId.AspNetCore.Azure/ActiveLogin.Authentication.BankId.AspNetCore.Azure.csproj, src/ActiveLogin.Authentication.BankId.AspNetCore.AzureMonitor/ActiveLogin.Authentication.BankId.AspNetCore.AzureMonitor.csproj, src/ActiveLogin.Authentication.BankId.AspNetCore.QRCoder/ActiveLogin.Authentication.BankId.AspNetCore.QRCoder.csproj, src/ActiveLogin.Authentication.BankId.AspNetCore.UAParser/ActiveLogin.Authentication.BankId.AspNetCore.UAParser.csproj, src/ActiveLogin.Authentication.BankId.AspNetCore/ActiveLogin.Authentication.BankId.AspNetCore.csproj, src/ActiveLogin.Authentication.BankId.AspNetCore/Areas/BankIdAuthentication/Views/BankId/_LoginScript.cshtml
Make sure that only one QR code refresh loop is active at all time.
Contributors: @tobylo @joanro123
=> Fix issue with multiple QR code refresh loops

src/ActiveLogin.Authentication.BankId.AspNetCore/Areas/ActiveLogin/Controllers/BankIdUiControllerBase.cs, src/Directory.Build.props
=> Fix ui options bug

src/ActiveLogin.Authentication.BankId.Core/IBankIdBuilderExtensions.cs
This PR fixes #384 .
Swap AddClientCertificate with UseClientCertificate.
=> Fix client certificate

src/ActiveLogin.Authentication.BankId.AspNetCore/Areas/ActiveLogin/Controllers/BankIdUiControllerBase.cs
This PR fixes #385.
Fix resource reference.
=> Fix resource reference

docs/articles/bankid.md
This PR updates the code snippet for a multi tenant scenario in the documentation
=> Fix doc - AddClientCertificate

docs/articles/bankid.md
=> Fixed broken link to demonstration.

docs/articles/bankid.md
=> Fix typo in bankid.md

src/ActiveLogin.Authentication.BankId.AzureKeyVault/AzureKeyVaultCertificateClient.cs
=> Fix for AzureKeyVaultCertificateClient on Macos, 

BREAKINGCHANGES.md, LICENSE.md, README.md, docs/articles/bankid.md, global.json, samples/IdentityServer.ClientSample/IdentityServer.ClientSample.csproj, samples/IdentityServer.ServerSample/IdentityServer.ServerSample.csproj, samples/IdentityServer.ServerSample/IdentityServerConfig.cs, samples/Standalone.MvcSample/Standalone.MvcSample.csproj, src/ActiveLogin.Authentication.BankId.Api/ActiveLogin.Authentication.BankId.Api.csproj, src/ActiveLogin.Authentication.BankId.AspNetCore/ActiveLogin.Authentication.BankId.AspNetCore.csproj, src/ActiveLogin.Authentication.BankId.AspNetCore/Auth/BankIdAuthHandler.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Sign/BankIdSignService.cs, src/ActiveLogin.Authentication.BankId.AzureKeyVault/ActiveLogin.Authentication.BankId.AzureKeyVault.csproj, src/ActiveLogin.Authentication.BankId.Core/ActiveLogin.Authentication.BankId.Core.csproj, src/ActiveLogin.Authentication.BankId.Core/BankIdBuilder.cs, src/Directory.Build.props, test/ActiveLogin.Authentication.BankId.Api.Test/ActiveLogin.Authentication.BankId.Api.Test.csproj, test/ActiveLogin.Authentication.BankId.AspNetCore.Test/ActiveLogin.Authentication.BankId.AspNetCore.Test.csproj, test/ActiveLogin.Authentication.BankId.AspNetCore.Test/BankId_UiAuth_Tests.cs, test/ActiveLogin.Authentication.BankId.AzureKeyVault.Test/ActiveLogin.Authentication.BankId.AzureKeyVault.Test.csproj, test/ActiveLogin.Authentication.BankId.Core.Test/ActiveLogin.Authentication.BankId.Core.Test.csproj, test/ActiveLogin.Authentication.BankId.UAParser.Test/ActiveLogin.Authentication.BankId.UAParser.Test.csproj, test/Directory.Build.props
=> Upgrade to .NET7

BREAKINGCHANGES.md, src/ActiveLogin.Authentication.BankId.Core/Flow/BankIdFlowService.cs, src/ActiveLogin.Authentication.BankId.Core/Launcher/BankIdDevelopmentLauncher.cs, src/ActiveLogin.Authentication.BankId.Core/Launcher/BankIdLauncher.cs, src/ActiveLogin.Authentication.BankId.Core/Launcher/IBankIdLauncher.cs, src/Directory.Build.props, test/ActiveLogin.Authentication.BankId.AspNetCore.Test/Helpers/TestBankIdLauncher.cs, test/ActiveLogin.Authentication.BankId.Core.Test/Helpers/TestBankIdLauncher.cs
Bump to version 7.
Also add Async suffix to `IBankIdLauncher.GetLaunchInfo`.
=> Bump to version 7

.github/workflows/build.yml, .github/workflows/release.yml, azure-pipelines.yml
=> Remove code signing

BREAKINGCHANGES.md, global.json, samples/IdentityServer.ClientSample/IdentityServer.ClientSample.csproj, samples/IdentityServer.ServerSample/IdentityServer.ServerSample.csproj, samples/Standalone.MvcSample/Standalone.MvcSample.csproj, src/ActiveLogin.Authentication.BankId.Api/ActiveLogin.Authentication.BankId.Api.csproj, src/ActiveLogin.Authentication.BankId.AspNetCore/ActiveLogin.Authentication.BankId.AspNetCore.csproj, src/ActiveLogin.Authentication.BankId.AspNetCore/Auth/BankIdAuthHandler.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/BankIdConstants.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/ClaimsTransformation/BankIdDefaultClaimsTransformer.cs, src/ActiveLogin.Authentication.BankId.AzureKeyVault/ActiveLogin.Authentication.BankId.AzureKeyVault.csproj, src/ActiveLogin.Authentication.BankId.AzureMonitor/ActiveLogin.Authentication.BankId.AzureMonitor.csproj, src/ActiveLogin.Authentication.BankId.Core/ActiveLogin.Authentication.BankId.Core.csproj, src/ActiveLogin.Authentication.BankId.QRCoder/ActiveLogin.Authentication.BankId.QRCoder.csproj, src/ActiveLogin.Authentication.BankId.UAParser/ActiveLogin.Authentication.BankId.UAParser.csproj, src/Directory.Build.props, test/ActiveLogin.Authentication.BankId.Api.Test/ActiveLogin.Authentication.BankId.Api.Test.csproj, test/ActiveLogin.Authentication.BankId.AspNetCore.Test/ActiveLogin.Authentication.BankId.AspNetCore.Test.csproj, test/ActiveLogin.Authentication.BankId.AspNetCore.Test/BankId_UiAuth_Tests.cs, test/ActiveLogin.Authentication.BankId.AspNetCore.Test/BankId_UiSign_Tests.cs, test/ActiveLogin.Authentication.BankId.AspNetCore.Test/ClaimsTransformation/BankIdDefaultClaimsTransformer_Tests.cs, test/ActiveLogin.Authentication.BankId.AzureKeyVault.Test/ActiveLogin.Authentication.BankId.AzureKeyVault.Test.csproj, test/ActiveLogin.Authentication.BankId.Core.Test/ActiveLogin.Authentication.BankId.Core.Test.csproj, test/ActiveLogin.Authentication.BankId.UAParser.Test/ActiveLogin.Authentication.BankId.UAParser.Test.csproj, test/Directory.Build.props
=> Upgrade to .NET 8

src/ActiveLogin.Authentication.BankId.AspNetCore/Client/activelogin-main.ts
This PR fixes #400.
If the user canceled the flow in the BankID app, the cancel button on the web page when returned to safari was hidden. Now it will be initialized.
=> Init cancel button on return

src/Directory.Build.props
=> Bump version to beta 1

ActiveLogin.Authentication.sln, README.md, samples/IdentityServer.ClientSample/IdentityServer.ClientSample.csproj, samples/IdentityServer.ServerSample/IdentityServer.ServerSample.csproj, samples/Phone.ConsoleSample/BankIdDemoHostedService.cs, samples/Phone.ConsoleSample/ConsoleHelper.cs, samples/Phone.ConsoleSample/Phone.ConsoleSample.csproj, samples/Phone.ConsoleSample/Program.cs, samples/Phone.ConsoleSample/SessionType.cs, samples/Phone.ConsoleSample/appsettings.json, src/ActiveLogin.Authentication.BankId.Api/ActiveLogin.Authentication.BankId.Api.csproj, src/ActiveLogin.Authentication.BankId.Api/BankIdSimulatedAppApiClient.cs, src/ActiveLogin.Authentication.BankId.Api/Models/CollectResponse.cs, src/ActiveLogin.Authentication.BankId.Api/Models/CollectResponseExtensions.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/ActiveLogin.Authentication.BankId.AspNetCore.csproj, src/ActiveLogin.Authentication.BankId.AzureKeyVault/ActiveLogin.Authentication.BankId.AzureKeyVault.csproj, src/ActiveLogin.Authentication.BankId.Core/ActiveLogin.Authentication.BankId.Core.csproj, src/Directory.Build.props, test/ActiveLogin.Authentication.BankId.Api.Test/ActiveLogin.Authentication.BankId.Api.Test.csproj, test/ActiveLogin.Authentication.BankId.Api.Test/BankIdAppApiClient_Tests.cs, test/ActiveLogin.Authentication.BankId.AspNetCore.Test/ActiveLogin.Authentication.BankId.AspNetCore.Test.csproj, test/ActiveLogin.Authentication.BankId.AzureKeyVault.Test/ActiveLogin.Authentication.BankId.AzureKeyVault.Test.csproj, test/ActiveLogin.Authentication.BankId.Core.Test/ActiveLogin.Authentication.BankId.Core.Test.csproj, test/ActiveLogin.Authentication.BankId.UAParser.Test/ActiveLogin.Authentication.BankId.UAParser.Test.csproj
=> Prep for V9

src/Directory.Build.props
Update version number to 10.0.0 RC 2
=> Update version number suffix.

global.json, samples/IdentityServer.ClientSample/IdentityServer.ClientSample.csproj, samples/IdentityServer.ServerSample/IdentityServer.ServerSample.csproj, samples/Phone.ConsoleSample/Phone.ConsoleSample.csproj, src/ActiveLogin.Authentication.BankId.Api/ActiveLogin.Authentication.BankId.Api.csproj, src/ActiveLogin.Authentication.BankId.AspNetCore/ActiveLogin.Authentication.BankId.AspNetCore.csproj, src/ActiveLogin.Authentication.BankId.AzureKeyVault/ActiveLogin.Authentication.BankId.AzureKeyVault.csproj, src/ActiveLogin.Authentication.BankId.Core/ActiveLogin.Authentication.BankId.Core.csproj, src/Directory.Build.props, test/ActiveLogin.Authentication.BankId.AspNetCore.Test/ActiveLogin.Authentication.BankId.AspNetCore.Test.csproj
- Upgrade NuGet packages.
- Upgrade .Net SDK.
=> Upgrade NuGet packages and .Net SDK

src/ActiveLogin.Authentication.BankId.UAParser/UAParserDeviceDetector.cs
fixes Performance improvement in UAParser #462
- Creates Parser only once and reuses it.
=> perf: cache Parser

src/Directory.Build.props
Release 10.1.0 RC 1. Change version number and update version number suffix.
=> Release 10.1.0 RC 1. Change version number

global.json, src/Directory.Build.props
Remove version suffix RC for release 10.1.0.
=> New release - version 10.1.0

src/ActiveLogin.Authentication.BankId.Api/Models/AuthRequest.cs, src/ActiveLogin.Authentication.BankId.Api/Models/Requirement.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Areas/ActiveLogin/Controllers/BankIdUiSignApiController.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Auth/BankIdAuthHandler.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Auth/BankIdAuthOptions.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/DataProtection/Serialization/BankIdUiOptionsSerializer.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/DataProtection/Serialization/BankIdUiStateSerializer.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Models/BankIdUiOptions.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Models/BankIdUiOptionsExtensions.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Sign/BankIdSignOptions.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Sign/BankIdSignProperties.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Sign/BankIdSignService.cs, src/ActiveLogin.Authentication.BankId.Core/Flow/BankIdFlowService.cs, src/ActiveLogin.Authentication.BankId.Core/Models/BankIdFlowOptions.cs, src/ActiveLogin.Authentication.BankId.Core/Models/BankIdSignData.cs, src/ActiveLogin.Authentication.BankId.Core/Requirements/BankIdAuthRequirements.cs, test/ActiveLogin.Authentication.BankId.AspNetCore.Test/BankId_UiAuth_Tests.cs, test/ActiveLogin.Authentication.BankId.AspNetCore.Test/BankId_UiSign_Tests.cs
This PR fixes #389, more information described [here](https://github.com/ActiveLogin/ActiveLogin.Authentication/issues/389)
=> feat(#389): add requirement cardreader

BREAKINGCHANGES.md, docs/articles/bankid.md, src/Directory.Build.props
- Increase version number and add version suffix
- Document breaking changes for 11.0.0.
=> Release version 11.0.0 RC 1

global.json, src/Directory.Build.props
Update release number to 11.0.
=> V 11 removed version suffix.
