ActiveLogin/ActiveLogin.Authentication

samples/IdentityServerSample/Controllers/AccountController.cs, samples/IdentityServerSample/Views/Shared/_Layout.cshtml, samples/MvcClientSample/Controllers/HomeController.cs, samples/MvcClientSample/Views/Shared/_Layout.cshtml, src/ActiveLogin.Authentication.BankId.Api/BankIdDevelopmentApiClient.cs, test/ActiveLogin.Authentication.BankId.Api.Test/BankIdDevelopmentApiClient_Tests.cs
This PR implements the logout buttons mentioned in #11
It includes changes that:
1. Adds logout button and functionality to the `MVC Client Sample`
2. Adds logout button and functionality to the `Identity Server Sample` 
3. Fixes a bug that prevented the user to perform more than one login attempt in a row in dev mode
4. Adds test to verify the bug fix mentioned above
=> Add logout buttons to samples

.gitignore, README.md, samples/IdentityServerSample/IdentityServerSample.csproj, samples/IdentityServerSample/Properties/launchSettings.json, samples/IdentityServerSample/appsettings.json, samples/MvcClientSample/Properties/launchSettings.json, samples/MvcClientSample/appsettings.json
This PR addresses the issues raised in #10 _(Simplify sample to run in dev mode out of the box)_
What it does:
1. Sets up predefined ports for the samples projects to run on. To make this work, it also modifies the `.gitignore` file to include the `launchSettings.json` files for the sample projects
2. Removes the missing certificates that prevents the projects to build
3. Adds a section in the main `README` file that explains how to run the samples
=> Make samples run in DEV mode without any additional configuration

src/ActiveLogin.Authentication.BankId.AspNetCore/BankIdAuthenticationBuilder.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/BankIdAuthenticationBuilderEnvironmentExtensions.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/BankIdAuthenticationBuilderExtensions.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/IBankIdAuthenticationBuilder.cs, src/ActiveLogin.Authentication.GrandId.AspNetCore/GrandIdAuthenticationBuilder.cs, src/ActiveLogin.Authentication.GrandId.AspNetCore/GrandIdAuthenticationBuilderEnvironmentExtensions.cs, src/ActiveLogin.Authentication.GrandId.AspNetCore/IGrandIdAuthenticationBuilder.cs
We did (indirect) register a real implementation of the BankID API as part of registering the HttpClient. Now it's separated and only enabled when calling Test/Prod environments for BankID/GrandID.
=> Fix HTTP Client registration

src/ActiveLogin.Authentication.BankId.Api/ActiveLogin.Authentication.BankId.Api.csproj, src/ActiveLogin.Authentication.BankId.AspNetCore.Azure/ActiveLogin.Authentication.BankId.AspNetCore.Azure.csproj, src/ActiveLogin.Authentication.BankId.AspNetCore/ActiveLogin.Authentication.BankId.AspNetCore.csproj, src/ActiveLogin.Authentication.Common/ActiveLogin.Authentication.Common.csproj, src/ActiveLogin.Authentication.GrandId.Api/ActiveLogin.Authentication.GrandId.Api.csproj, src/ActiveLogin.Authentication.GrandId.AspNetCore/ActiveLogin.Authentication.GrandId.AspNetCore.csproj
The reference to the common package had been handled wrong. It should now be fixed.
This solves https://github.com/ActiveLogin/ActiveLogin.Authentication/issues/26
=> Fix common reference

samples/IdentityServer.ClientSample/Startup.cs, samples/IdentityServer.ServerSample/Startup.cs, samples/Standalone.MvcSample/Startup.cs
We did not validate the AntiforgeryToken when doing logout. The samples are now updated with a policy to always require it when relevant.
=> Add validation of AntiforgeryToken in the samples

README.md, src/ActiveLogin.Authentication.BankId.AspNetCore/Areas/BankIdAuthentication/Controllers/BankIdApiController.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/BankIdClaimTypes.cs, src/ActiveLogin.Authentication.GrandId.AspNetCore/GrandIdClaimTypes.cs
Adds badges for our SonarCube/SonarCloud scan (https://sonarcloud.io/dashboard?id=ActiveLogin_ActiveLogin.Authentication).
Also fixes three things found
- Public static properties that should be constants
- Simplier syntax for setting cert policies to not hit bug report
=> Add SonarCloud badges and fix bugs found

src/ActiveLogin.Authentication.BankId.AspNetCore/Areas/BankIdAuthentication/Controllers/BankIdController.cs
This is required in Swagger 2.0.
Yes, We know this is intended for a web, but we are evaluating it for our backend api.
Error message:
```
System.NotSupportedException: 'Ambiguous HTTP method for action - ActiveLogin.Authentication.BankId.AspNetCore.Areas.BankIdAuthentication.Controllers.BankIdController.Login (ActiveLogin.Authentication.BankId.AspNetCore). Actions require an explicit HttpMethod binding for Swagger 2.0'
```
Fixes #121.
=> Added Http method on action

src/ActiveLogin.Authentication.BankId.AspNetCore/BankIdAuthenticationHandler.cs, test/ActiveLogin.Authentication.BankId.AspNetCore.Test/BankId_Authentication_Tests.cs
By adding the path base to the login and callback paths we can support using
routing maps in the `IApplicationBuilder`. Since the default path base is '/' this
should not affect users who have not defined mappings.
This PR solves issue #123
=> Add request path base to login and callback path

samples/IdentityServer.ServerSample/Startup.cs
The identity server example was broken by 3.0 update. This fixes the issue by adding authorization to the pipeline since it is required by identityserver.
Ref #131
=> Add use authorization to support IdentityServer controller

src/ActiveLogin.Authentication.BankId.AspNetCore/Areas/BankIdAuthentication/Controllers/BankIdApiController.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Areas/BankIdAuthentication/Controllers/BankIdController.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Areas/BankIdAuthentication/Models/BankIdCancelApiStatusRequest.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Areas/BankIdAuthentication/Models/BankIdLoginApiCancelRequest.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Areas/BankIdAuthentication/Models/BankIdLoginApiCancelResponse.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Areas/BankIdAuthentication/Models/BankIdLoginScriptOptions.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Areas/BankIdAuthentication/Views/BankId/_LoginScript.cshtml, src/ActiveLogin.Authentication.BankId.AspNetCore/Areas/BankIdAuthentication/Views/BankId/_LoginStatus.cshtml, src/ActiveLogin.Authentication.BankId.AspNetCore/BankIdLoggingEvents.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/LoggerExtensions.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Resources/BankIdAuthenticationHandler.Designer.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Resources/BankIdAuthenticationHandler.resx, src/ActiveLogin.Authentication.BankId.AspNetCore/Resources/BankIdAuthenticationHandler.sv.resx, test/ActiveLogin.Authentication.BankId.AspNetCore.Test/BankId_Authentication_Tests.cs
This commit adds a cancel button to the status view. When clicked the button triggers a post request to a new endpoint in the BankIdApiController. The new endpoint then asks the BankID client to cancel the outstanding authentication request.
If the cancellation is successful, control is returned to the GUI where the status information is hidden and the form field and buttons for initiating a BankID authn request are once again visible.
If an error occurs, the status of the error is displayed as in the check status call. Let's open a new feature request to add/redirect the user to something more meaningful: #135 .
Ref ActiveLogin/ActiveLogin.Authentication#119
=> Add cancel button to abort BankID auth requests

docs/getting-started-bankid.md
This was discussed extensively in ActiveLogin/ActiveLogin.Authentication#144. Basically
certificates with private keys are inly exposed as _secrets_ in keyvalt. The
_certificates_ endpoint will only return the crt.
Ref ActiveLogin/ActiveLogin.Authentication#148
=> Clarify why we fetch certificates as secrets

src/ActiveLogin.Authentication.BankId.AspNetCore/Areas/BankIdAuthentication/Controllers/BankIdApiController.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Areas/BankIdAuthentication/Models/BankIdLoginApiErrorResponse.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Areas/BankIdAuthentication/Models/BankIdLoginApiStatusRequest.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Areas/BankIdAuthentication/Models/BankIdLoginApiStatusResponse.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Areas/BankIdAuthentication/Views/BankId/_LoginScript.cshtml
This commit adds a retry mechanism for error results with
hint StartFailed. It will retry 5 times before giving up.
Lets see where we can take this naive approach.
=> Add retries for StartFailed hints

README.md
=> Add info on Cookies

azure-pipelines.yml
Publishes a self contained app as Azure App Service can't runt Core 3.1.
=> Fix broken samples in Azure

src/ActiveLogin.Authentication.BankId.Api/Models/ErrorCode.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Areas/BankIdAuthentication/Controllers/BankIdApiController.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/BankIdLoggingEvents.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/LoggerExtensions.cs
This commit will swallow any request error between the API and the
BankID service when the user tries to cancel. When a user cancels,
they only have one way back to restart the authentication process
and that is through the cancellation button.
We still keep the validation for order reference and cancel url
though since we want to protect against bad requests coming in
and potential redirection attacks.
This PR fixes #184 
=> Provide validated cancellation URL for all BankID cancellations

src/ActiveLogin.Authentication.BankId.Api/Models/AuthResponse.cs, src/ActiveLogin.Authentication.BankId.Api/Models/CancelResponse.cs, src/ActiveLogin.Authentication.BankId.Api/Models/CollectResponse.cs, src/ActiveLogin.Authentication.BankId.Api/Models/CompletionData.cs, src/ActiveLogin.Authentication.BankId.Api/Models/Device.cs, src/ActiveLogin.Authentication.BankId.Api/Models/SignResponse.cs, src/ActiveLogin.Authentication.BankId.Api/Models/User.cs, src/ActiveLogin.Authentication.GrandId.Api/Models/BankIdFederatedLoginResponse.cs, src/ActiveLogin.Authentication.GrandId.Api/Models/BankIdGetSessionResponse.cs, src/ActiveLogin.Authentication.GrandId.Api/Models/BankIdGetSessionUserAttributes.cs, src/ActiveLogin.Authentication.GrandId.Api/Models/LogoutResponse.cs
=> Make response objects for API public

README.md, src/ActiveLogin.Authentication.BankId.Api/ActiveLogin.Authentication.BankId.Api.csproj, src/ActiveLogin.Authentication.BankId.Api/README.md, src/ActiveLogin.Authentication.BankId.AspNetCore.Azure/ActiveLogin.Authentication.BankId.AspNetCore.Azure.csproj, src/ActiveLogin.Authentication.BankId.AspNetCore.Azure/README.md, src/ActiveLogin.Authentication.BankId.AspNetCore.QRCoder/ActiveLogin.Authentication.BankId.AspNetCore.QRCoder.csproj, src/ActiveLogin.Authentication.BankId.AspNetCore.QRCoder/README.md, src/ActiveLogin.Authentication.BankId.AspNetCore/ActiveLogin.Authentication.BankId.AspNetCore.csproj, src/ActiveLogin.Authentication.BankId.AspNetCore/README.md, src/ActiveLogin.Authentication.GrandId.Api/ActiveLogin.Authentication.GrandId.Api.csproj, src/ActiveLogin.Authentication.GrandId.Api/README.md, src/ActiveLogin.Authentication.GrandId.AspNetCore/ActiveLogin.Authentication.GrandId.AspNetCore.csproj, src/ActiveLogin.Authentication.GrandId.AspNetCore/README.md
This PR fixes #165.
Turns out that the markdown integration on NuGet.org is manual only at this time.
The readme.md will be packed as readme.txt as that is the current format nuget in visual studio will undertand.
https://github.com/NuGet/Home/wiki/Packaging-Documentation-within-the-nupkg
=> Add readme files to the packages

docs/getting-started-bankid.md, samples/IdentityServer.ServerSample/appsettings.json, samples/Standalone.MvcSample/appsettings.json, src/ActiveLogin.Authentication.BankId.AspNetCore.Azure/BankIdBuilderAzureExtensions.cs, src/ActiveLogin.Authentication.BankId.AspNetCore.Azure/ClientCertificateFromAzureKeyVaultOptions.cs, src/ActiveLogin.Authentication.BankId.AspNetCore.Azure/readme.txt, test/ActiveLogin.Authentication.BankId.AspNetCore.Azure.Test/BankIdAuthenticationBuilderAzureExtensions_Tests.cs
This PR will clarify the naming of the certificate/secret name in
the options for using client certificates in Azure.
This PR fixes #208 .
=> Change secret key to secret name for azure certificates

src/ActiveLogin.Authentication.BankId.Api/Models/Cert.cs
This PR will expose the Cert data contract constructor
so objects can be build outside of the package. This is needed
to be able to implement a custom simulated client for BankID.
This PR fixes #210
=> Make Cert data contract publicly available

src/ActiveLogin.Authentication.BankId.AspNetCore/Areas/BankIdAuthentication/Controllers/BankIdApiController.cs
=> Fix bug with EndUserIp IPv4 mapped to IPv6

src/ActiveLogin.Authentication.BankId.AspNetCore/Areas/BankIdAuthentication/Controllers/BankIdApiController.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/BankIdConstants.cs, test/ActiveLogin.Authentication.BankId.AspNetCore.Test/BankId_Authentication_Tests.cs
=> Forces json reponses to always use camelCasing

src/ActiveLogin.Authentication.BankId.AspNetCore/Areas/BankIdAuthentication/Controllers/BankIdApiController.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Launcher/BankIdLauncher.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/SupportedDevice/BankIdSupportedDevice.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/SupportedDevice/BankIdSupportedDeviceDetector.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/SupportedDevice/BankIdSupportedDeviceOsVersion.cs, test/ActiveLogin.Authentication.BankId.AspNetCore.Test/UserMessage/BankIdSupportedDeviceDetector_Detect_Tests.cs
Fixes #242.
Detect device Os version for Android and change redirect scheme for Android version >= 6 as per new guidelines.
=> Change redirect scheme for android (242)

ActiveLogin.Authentication.sln, docs/tests/bankid-app-launch-tests-auto-bankid.html, docs/tests/bankid-app-launch-tests-auto-https.html, docs/tests/bankid-app-launch-tests.html, src/ActiveLogin.Authentication.BankId.AspNetCore/Areas/BankIdAuthentication/Controllers/BankIdApiController.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Areas/BankIdAuthentication/Models/BankIdLoginApiInitializeResponse.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Areas/BankIdAuthentication/Views/BankId/_LoginScript.cshtml, src/ActiveLogin.Authentication.BankId.AspNetCore/Launcher/BankIdDevelopmentLauncher.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Launcher/BankIdLauncher.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Launcher/IBankIdLauncher.cs, test/ActiveLogin.Authentication.BankId.AspNetCore.Test/Helpers/TestBankIdLauncher.cs
This PR fixes #251 and fixes #252.
=> Fix app launch on Android

README.md, src/ActiveLogin.Authentication.BankId.Api/ActiveLogin.Authentication.BankId.Api.csproj, src/ActiveLogin.Authentication.BankId.AspNetCore.Azure/ActiveLogin.Authentication.BankId.AspNetCore.Azure.csproj, src/ActiveLogin.Authentication.BankId.AspNetCore.AzureMonitor/ActiveLogin.Authentication.BankId.AspNetCore.AzureMonitor.csproj, src/ActiveLogin.Authentication.BankId.AspNetCore.AzureMonitor/BankIdApplicationInsightsEventListener.cs, src/ActiveLogin.Authentication.BankId.AspNetCore.QRCoder/ActiveLogin.Authentication.BankId.AspNetCore.QRCoder.csproj, src/ActiveLogin.Authentication.BankId.AspNetCore/ActiveLogin.Authentication.BankId.AspNetCore.csproj, src/ActiveLogin.Authentication.BankId.AspNetCore/Areas/BankIdAuthentication/Controllers/BankIdApiController.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Events/BankIdAuthErrorEvent.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Events/BankIdAuthSuccessEvent.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Events/Infrastructure/BankIdEventTrigger.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Launcher/BankIdDevelopmentLauncher.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Launcher/BankIdLaunchInfo.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Launcher/BankIdLauncher.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Launcher/IBankIdLauncher.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/SupportedDevice/BankIdSupportedDevice.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/SupportedDevice/BankIdSupportedDeviceBrowser.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/SupportedDevice/BankIdSupportedDeviceDetector.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/SupportedDevice/BankIdSupportedDeviceOsVersion.cs, test/ActiveLogin.Authentication.BankId.AspNetCore.Test/Helpers/TestBankIdLauncher.cs, test/ActiveLogin.Authentication.BankId.AspNetCore.Test/UserMessage/BankIdSupportedDeviceDetector_Detect_Tests.cs
This PR is related to #242, #251, #252
=> Add support for Samsung Internet Browser and Opera on Android

src/ActiveLogin.Authentication.BankId.AspNetCore/Events/BankIdAspNetAuthenticateSuccessEvent.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Events/Infrastructure/BankIdDebugEventListener.cs, test/ActiveLogin.Authentication.BankId.AspNetCore.Test/Events/Infrastructure/BankIdDebugEventListener_Tests.cs, test/ActiveLogin.Authentication.BankId.AspNetCore.Test/Helpers/TestDeepBankIdEvent.cs
=> Fix failing debug logger

src/ActiveLogin.Authentication.BankId.AspNetCore/Areas/BankIdAuthentication/Controllers/BankIdApiController.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/BankIdBuilderExtensions.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/EndUserContext/BankIdDynamicEndUserIpResolver.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/EndUserContext/BankIdRemoteIpAddressEndUserIpResolver.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/EndUserContext/IBankIdEndUserIpResolver.cs
=> Add BankId prefix to end user ip resolver

src/ActiveLogin.Authentication.BankId.AspNetCore/Areas/BankIdAuthentication/Models/BankIdLoginApiCancelRequest.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Areas/BankIdAuthentication/Models/BankIdLoginApiInitializeRequest.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Areas/BankIdAuthentication/Models/BankIdLoginApiStatusRequest.cs
In .NET 5, it seems as though the JSON deserialization currently requires public constructors for it to work. Because of this, I have updated the constructors for the request models to make sure it works.
=> Made model constructors public to enable deserialization

src/ActiveLogin.Authentication.BankId.Api/BankIdHttpClientExtensions.cs, src/ActiveLogin.Authentication.BankId.Api/BankIdSimulatedApiClient.cs, src/ActiveLogin.Authentication.BankId.Api/Models/AuthResponse.cs, src/ActiveLogin.Authentication.BankId.Api/Models/Requirement.cs, src/ActiveLogin.Authentication.BankId.Api/Models/SignResponse.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Areas/BankIdAuthentication/Controllers/BankIdApiController.cs, test/ActiveLogin.Authentication.BankId.Api.Test/BankIdApiClient_Tests.cs
This PR fixes #275 .
Added a simplified fallback on autoStartTokenRequired for backward compatiblitity (string.replace). Thought about adding another class for v5 regarding requirement or changing it on serialization but felt a bit overkill. One perhaps could add both datamembers as well.
I've tried it out with generation of qr token with:
```csharp
public AuthResponse Response { get; }
public DateTime InitTime { get; } = DateTime.Now;
/// <summary>
/// Calculates QR token according to https://www.bankid.com/utvecklare/guider/teknisk-integrationsguide/qrkoder
/// </summary>
/// <param name="orderref"></param>
/// <returns></returns>
public string GetQrToken(string orderref)
{
if(Response?.OrderRef is string refOrderRef &&
string.Equals(refOrderRef, orderref, …
```
=> Add response for animated Qr tokens

docs/bankid.md, samples/IdentityServer.ServerSample/Program.cs, src/ActiveLogin.Authentication.BankId.Api/ActiveLogin.Authentication.BankId.Api.csproj, src/ActiveLogin.Authentication.BankId.Api/BankIdApiClientExtensions.cs, src/ActiveLogin.Authentication.BankId.Api/Models/AuthRequest.cs, src/ActiveLogin.Authentication.BankId.AspNetCore.Azure/ActiveLogin.Authentication.BankId.AspNetCore.Azure.csproj, src/ActiveLogin.Authentication.BankId.AspNetCore.AzureMonitor/ActiveLogin.Authentication.BankId.AspNetCore.AzureMonitor.csproj, src/ActiveLogin.Authentication.BankId.AspNetCore.QRCoder/ActiveLogin.Authentication.BankId.AspNetCore.QRCoder.csproj, src/ActiveLogin.Authentication.BankId.AspNetCore.UAParser/ActiveLogin.Authentication.BankId.AspNetCore.UAParser.csproj, src/ActiveLogin.Authentication.BankId.AspNetCore/ActiveLogin.Authentication.BankId.AspNetCore.csproj, src/ActiveLogin.Authentication.BankId.AspNetCore/Areas/BankIdAuthentication/Controllers/BankIdApiController.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/BankIdAuthRequestContext.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/BankIdAuthRequestEmptyUserDataResolver.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/BankIdAuthRequestStaticUserDataResolver.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/BankIdAuthUserData.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/BankIdBuilderExtensions.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/IBankIdAuthRequestUserDataResolver.cs, test/ActiveLogin.Authentication.BankId.Api.Test/BankIdApiClientExtensions_Tests.cs, test/ActiveLogin.Authentication.BankId.Api.Test/BankIdApiClient_Tests.cs
=> Support for user data on auth request

src/ActiveLogin.Authentication.BankId.AspNetCore/Areas/ActiveLogin/Controllers/BankIdUiApiControllerBase.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/BankIdConstants.cs
This PR fixes #373.
- [-] Test added
- [-] Documentation updated / written
=> Decoupled JSON serialization from system defined serialization

README.md, src/ActiveLogin.Authentication.BankId.AspNetCore/ActiveLogin.Authentication.BankId.AspNetCore.csproj, src/ActiveLogin.Authentication.BankId.AspNetCore/Client/activelogin-main.ts
This PR fixes #433.
Adds 3 retries (with 1000ms delay inbetween) for `initialize`, `checkStatus` and `refreshQrCode`.
=> Add client side retry logic

BREAKINGCHANGES.md, docs/articles/bankid.md, src/ActiveLogin.Authentication.BankId.Core/Launcher/BankIdLauncher.cs, src/ActiveLogin.Authentication.BankId.Core/Launcher/BankIdLauncherCustomBrowserConfig.cs, src/Directory.Build.props
Move the custom redirect part of the code to be able to override redirects even if it isn't an iphone and rename the return url from iosReturnUrl to ReturnUrl. 
This makes it possible for TWA (wrapped PWA) to use a user agent without faking being anything else.
This PR fixes #442 .
=> AddCustomBrowserByUserAgent will always override regardless of device

README.md, docs/articles/bankid.md, src/ActiveLogin.Authentication.BankId.Api/ActiveLogin.Authentication.BankId.Api.csproj, src/ActiveLogin.Authentication.BankId.Api/BankIdApiConverters.cs, src/ActiveLogin.Authentication.BankId.Api/BankIdAppApiClient.cs, src/ActiveLogin.Authentication.BankId.Api/BankIdAppApiClientExtensions.cs, src/ActiveLogin.Authentication.BankId.Api/BankIdSimulatedAppApiClient.cs, src/ActiveLogin.Authentication.BankId.Api/IBankIdAppApiClient.cs, src/ActiveLogin.Authentication.BankId.Api/Models/CallInitiator.cs, src/ActiveLogin.Authentication.BankId.Api/Models/CollectResponseExtensions.cs, src/ActiveLogin.Authentication.BankId.Api/Models/PhoneAuthRequest.cs, src/ActiveLogin.Authentication.BankId.Api/Models/PhoneAuthResponse.cs, src/ActiveLogin.Authentication.BankId.Api/Models/PhoneRequest.cs, src/ActiveLogin.Authentication.BankId.Api/Models/PhoneRequirement.cs, src/ActiveLogin.Authentication.BankId.Api/Models/PhoneResponse.cs, src/ActiveLogin.Authentication.BankId.Api/Models/PhoneSignRequest.cs, src/ActiveLogin.Authentication.BankId.Api/Models/PhoneSignResponse.cs, src/ActiveLogin.Authentication.BankId.Api/README.md, test/ActiveLogin.Authentication.BankId.Api.Test/BankIdAppApiClientExtensions_Tests.cs, test/ActiveLogin.Authentication.BankId.Api.Test/BankIdAppApiClient_Tests.cs, test/ActiveLogin.Authentication.BankId.Api.Test/BankIdSimulatedAppApiClient_Tests.cs, test/ActiveLogin.Authentication.BankId.Api.Test/Models/PhoneRequest_Tests.cs, test/ActiveLogin.Authentication.BankId.Api.Test/Models/Request_Tests.cs, test/ActiveLogin.Authentication.BankId.AspNetCore.Test/BankId_Ui_Tests_Base.cs
=> Implement phone API support

samples/IdentityServer.ClientSample/IdentityServer.ClientSample.csproj, samples/IdentityServer.ServerSample/IdentityServer.ServerSample.csproj, src/ActiveLogin.Authentication.BankId.AspNetCore/ActiveLogin.Authentication.BankId.AspNetCore.csproj, src/ActiveLogin.Authentication.BankId.AzureKeyVault/ActiveLogin.Authentication.BankId.AzureKeyVault.csproj, test/ActiveLogin.Authentication.BankId.Api.Test/ActiveLogin.Authentication.BankId.Api.Test.csproj, test/ActiveLogin.Authentication.BankId.AspNetCore.Test/ActiveLogin.Authentication.BankId.AspNetCore.Test.csproj, test/ActiveLogin.Authentication.BankId.AzureKeyVault.Test/ActiveLogin.Authentication.BankId.AzureKeyVault.Test.csproj, test/ActiveLogin.Authentication.BankId.Core.Test/ActiveLogin.Authentication.BankId.Core.Test.csproj, test/ActiveLogin.Authentication.BankId.UAParser.Test/ActiveLogin.Authentication.BankId.UAParser.Test.csproj
Bumps [Azure.Identity] from 1.11.2 to 1.12.6.
Bumps [Duende.IdentityServer] from 7.0.4 to 7.0.5.
Bumps [Microsoft.AspNetCore.Authentication.OpenIdConnect] from 8.0.4 to 8.0.6.
Bumps [Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation] from 8.0.4 to 8.0.6.
Bumps [Microsoft.AspNetCore.Mvc.Testing] from 8.0.4 to 8.0.6.
Bumps [Microsoft.AspNetCore.TestHost] from 8.0.4 to 8.0.6.
Bumps [Microsoft.NET.Test.Sdk] from 17.9.0 to 17.10.0.
Bumps [Microsoft.TypeScript.MSBuild] from 5.4.4 to 5.4.5.
Bumps [xunit] from 2.8.0 to 2.8.1.
Bumps [xunit.runner.visualstudio] from 2.8.0 to 2.8.1.
=> Upgrade Nuget packages.

src/ActiveLogin.Authentication.BankId.Api/ActiveLogin.Authentication.BankId.Api.csproj, src/ActiveLogin.Authentication.BankId.Core/Flow/BankIdFlowService.cs
This PR fixes #471.
- This is a minor fix related to Signing. When `flowOptions.AllowedRiskLevel` is set to `Risk.BankIdAllowedRiskLevel.NoRiskLevel,` the risk was incorrectly set to the value `"norisklevel",` which is invalid in the BankID API v6.0. Instead, if `NoRiskLevel` is specified, risk will no longer be set.
- Updated the NuGet package System.Text.Json to version 8.0.5 to address a known high-severity vulnerability in version 8.0.4. Details can be found here: https://github.com/advisories/GHSA-8g4q-xg66-9fp4
=> Do not set risk in GetSignRequest when AllowedRiskLevel is NoRiskLevel

docs/articles/bankid.md, global.json, src/ActiveLogin.Authentication.BankId.Api/Models/Requirement.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Areas/ActiveLogin/Controllers/BankIdUiSignApiController.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Auth/AuthenticationBuilderBankIdExtensions.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Auth/IBankIdAuthBuilderExtensions.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/DataProtection/Serialization/BankIdUiStateSerializer.cs, src/ActiveLogin.Authentication.BankId.AspNetCore/Sign/BankIdSignProperties.cs, src/ActiveLogin.Authentication.BankId.Core/Flow/BankIdFlowService.cs, src/ActiveLogin.Authentication.BankId.Core/Models/BankIdSignData.cs, src/ActiveLogin.Authentication.BankId.Core/Requirements/BankIdAuthRequestEmptyRequirementsResolver.cs, src/ActiveLogin.Authentication.BankId.Core/Requirements/BankIdAuthRequirements.cs, src/ActiveLogin.Authentication.BankId.Core/Requirements/IBankIdAuthRequestRequirementsResolver.cs, src/ActiveLogin.Authentication.BankId.Core/ServiceCollectionBankIdExtensions.cs, src/ActiveLogin.Authentication.BankId.Core/UserData/BankIdAuthUserData.cs, test/ActiveLogin.Authentication.BankId.Api.Test/BankIdAppApiClient_Tests.cs
=> Set requirements on how the authentication or signing order must be performed dynamically

samples/IdentityServer.ServerSample/Controllers/AccountController.cs, samples/IdentityServer.ServerSample/Views/Account/Login.cshtml
Fixes [https://github.com/ActiveLogin/ActiveLogin.Authentication/security/code-scanning/124](https://github.com/ActiveLogin/ActiveLogin.Authentication/security/code-scanning/124)
To fix the cross-site scripting vulnerability, we need to sanitize the `returnUrl` parameter before rendering it in the view. The best way to do this is to use the `System.Net.WebUtility.HtmlEncode` method to encode the `returnUrl` value. This will ensure that any potentially malicious scripts in the `returnUrl` are rendered as plain text and not executed by the browser.
We will make the following changes:
1. Sanitize the `returnUrl` parameter in the `AccountController` before passing it to the view.
2. Update the `Login.cshtml` view to use the sanitized `returnUrl`.
_Suggested fixes powered by Copilot Autofix. …
=> Fix code scanning alert no. 124: Cross-site scripting

docs/articles/bankid.md, src/ActiveLogin.Authentication.BankId.Api/BankIdErrorSimulatedApiClientDecorator.cs, src/ActiveLogin.Authentication.BankId.Core/Events/Infrastructure/BankIdDebugEventListener.cs, src/ActiveLogin.Authentication.BankId.Core/IBankIdBuilderExtensions.cs, test/ActiveLogin.Authentication.BankId.Api.Test/ActiveLogin.Authentication.BankId.Api.Test.csproj, test/ActiveLogin.Authentication.BankId.Api.Test/BankIdErrorSimulatedAppApiClientDecorator_Tests.cs, test/ActiveLogin.Authentication.BankId.AspNetCore.Test/ActiveLogin.Authentication.BankId.AspNetCore.Test.csproj, test/ActiveLogin.Authentication.BankId.Core.Test/BankIdBuilder_Tests.cs
This PR fixes #270.
New feature to simulate BankID API errors for development and testing.
Introduced functionality to simulate BankID API errors and added related documentation and tests.
- `bankid.md`: Documented how to simulate BankID API errors using `AddSimulatedBankIdApiError`.
- `BankIdErrorSimulatedApiClientDecorator.cs`: Added a decorator class to simulate errors from the BankID API.
- `IBankIdBuilderExtensions.cs`: Added an extension method to integrate simulated API errors into the BankID API client.
- `BankIdErrorSimulatedAppApiClientDecorator_Tests.cs`: Created tests for the error simulation decorator.
- `BankIdBuilder_Tests.cs`: Added tests to ensure proper handling of simulated API errors in the service collection.
=> Simulated API errors

global.json, samples/IdentityServer.ClientSample/IdentityServer.ClientSample.csproj, samples/IdentityServer.ServerSample/IdentityServer.ServerSample.csproj, samples/Phone.ConsoleSample/Phone.ConsoleSample.csproj, samples/Standalone.MvcSample/Standalone.MvcSample.csproj, src/ActiveLogin.Authentication.BankId.Api/ActiveLogin.Authentication.BankId.Api.csproj, src/ActiveLogin.Authentication.BankId.AspNetCore/ActiveLogin.Authentication.BankId.AspNetCore.csproj, src/ActiveLogin.Authentication.BankId.AzureKeyVault/ActiveLogin.Authentication.BankId.AzureKeyVault.csproj, src/ActiveLogin.Authentication.BankId.AzureKeyVault/AzureKeyVaultCertificateClient.cs, src/ActiveLogin.Authentication.BankId.Core/ActiveLogin.Authentication.BankId.Core.csproj, src/ActiveLogin.Authentication.BankId.Core/BankIdCertificates.cs, src/ActiveLogin.Authentication.BankId.Core/IBankIdBuilderExtensions.cs, src/Directory.Build.props, test/ActiveLogin.Authentication.BankId.Api.Test/ActiveLogin.Authentication.BankId.Api.Test.csproj, test/ActiveLogin.Authentication.BankId.AspNetCore.Test/ActiveLogin.Authentication.BankId.AspNetCore.Test.csproj, test/ActiveLogin.Authentication.BankId.AzureKeyVault.Test/ActiveLogin.Authentication.BankId.AzureKeyVault.Test.csproj, test/ActiveLogin.Authentication.BankId.Core.Test/ActiveLogin.Authentication.BankId.Core.Test.csproj, test/ActiveLogin.Authentication.BankId.UAParser.Test/ActiveLogin.Authentication.BankId.UAParser.Test.csproj, test/Directory.Build.props
Revert to .Net 8 since certificate issues in .Net 9 is not yet resolved. See issue #484.
=> Revert to .Net 8 since certificate issues in .Net 9 is not yet resolved.
